adcake/portfolio/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from multimedia.models import Image
from models import Gallery

# Portfolio ----
urlpatterns = patterns('portfolio.views',
    url(r'edit/$', 'view_portfolio', name='my_portfolio'),
    url(r'xhr/reorder_branches/$', 'xhr_reorder_branches', name='portfolio_xhr_reorder_branches'),
    url(r'xhr/save_description/$', 'xhr_save_description', name='portfolio_xhr_save_description'),
    url(r'xhr/(?P<branch>(video|audio|gallery))/reorder/$', 'xhr_reorder_branch', name='portfolio_xhr_reorder_branch'),
    url(r'xhr/(?P<branch>(video|audio|gallery))/add_items/$', 'xhr_add', name='portfolio_xhr_add'),
    url(r'xhr/(?P<branch>(video|audio|gallery))/create_items/$', 'xhr_create', name='portfolio_xhr_create'),
    url(r'xhr/(?P<branch>(video|audio|gallery))/delete_item/$', 'xhr_delete', name='portfolio_xhr_delete'),
)

# Galleries ----
gallery_info = {
    'paginate_by': 12,
    'template_object_name': 'gallery',
}

gallery_delete = {
    'model': Gallery,
    'template_object_name': 'gallery',
}

urlpatterns += patterns('portfolio.views',
    url(r'(?P<username>[\w.-]+)/galleries/$', 'gallery_list', gallery_info, name='galleries_for'),
    url(r'(?P<username>[\w.-]+)/galleries/page(?P<page>[0-9]+)/$', 'gallery_list', gallery_info, name='galleries_page_for'),
    url(r'(?P<username>[\w.-]+)/galleries/delete/(?P<object_id>[0-9]+)/$', 'gallery_delete', gallery_delete, name='gallery_confirm_delete'),
    url(r'(?P<username>[\w.-]+)/galleries/delete/complete/$', direct_to_template, {'template': 'gallery_complete_delete.html'}, name='gallery_complete_delete'),
    # URL for 'add a new gallery'
    # URL for 'edit this gallery'
)

# Images ----
urlpatterns += patterns('portfolio.views',
    url(r'(?P<username>[\w.-]+)/galleries/(?P<slug>[\w\-]+)/$', 'gallery_detail', dict(slug_field='slug', template_object_name='gallery'), name='gallery_detail'),
    url(r'(?P<username>[\w.-]+)/images/(?P<image_id>\d+)/$', 'image_detail_portfolio', name='image_detail_portfolio'),
    url(r'(?P<username>[\w.-]+)/galleries/(?P<g_slug>[\w\-]+)/(?P<slug>[\w\-]+)/$', 'image_detail', dict(slug_field='slug', gallery_slug_field='slug', queryset=Image.objects.all(), template_name='portfolio/image_detail.html', template_object_name='image'), name='image_detail'),
    # URL for 'add a new image to this gallery'
    # URL for 'edit this image'
)

# Administration ----
urlpatterns += patterns('portfolio.views',
    url(r'gallery_detail/administration/$', 'gallery_detail_administration', name='gallery_detail_administration'),
    url(r'gallery_detail/delete_image/$', 'gallery_detail_delete_image', name='gallery_detail_delete_image'),
    url(r'video/delete/$', 'video_delete', name='video_delete'),
    url(r'gallery/delete/$', 'gallery_delete', name='gallery_delete'),
)



# Portfolio, user view
urlpatterns += patterns('portfolio.views',
    url(r'(?P<username>[\w.-]+)/$', 'view_portfolio', name='portfolio_for'),
)

adcake/rabidratings/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^submit', 'rabidratings.views.record_vote'),
    (r'^test', 'rabidratings.views.testview')
    )

adcake/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from directory.urls import company_detail
from portfolio.views import view_portfolio
from django.views.generic import list_detail
import settings
from django.contrib import admin
import oembed
# Uncomment the next two lines to enable the admin:
oembed.autodiscover()
admin.autodiscover()
#import haystack
#haystack.autodiscover()
from contact.views import contact
from views import homepage, view_port_for
#from views import SearchView

urlpatterns = patterns('',
    # Example:
    # (r'^adcake/', include('foo.urls')),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^estramboticaanastacia/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    # (r'^estramboticaanastacia/filebrowser/', include('filebrowser.urls')),
    (r'^estramboticaanastacia/eretriever/', include('email-retriever.urls')),
    (r'^estramboticaanastacia/', include(admin.site.urls)),
    # Haystack
    #(r'^search/', SearchView(), {}, 'search'),
    (r'^$', homepage, {}, 'homepage'),
    (r'^accounts/', include('accounts.urls')),
    (r'^cake/', include('cake.urls')),
    (r'^directory/', include('directory.urls')),
    (r'^galleries/', include('portfolio.galleries_urls')),
    (r'^images/', include('multimedia.images_urls')),
    (r'^messages/', include('messages.urls')),
    (r'^news/', include('news.urls')),
    (r'^portfolio/', include('portfolio.urls')),
    (r'^professionals/', include('professionals.urls')),
    (r'^accounts/', include('invitation.urls')),
    (r'^accounts/', include('registration.urls')),    
#    (r'^registration/', include('registration.urls')),
    (r'^skills/', include('skills.urls')),
    (r'^videos/', include('multimedia.videourls')),
    (r'^multimedia/', include('multimedia.urls')),
    (r'^resume/', include('resume.urls')),
    (r'^profile/', include('profiles.urls')),
    (r'^jobs/', include('jobs.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    url(r'^terms', direct_to_template, {'template':'terms_of_use.html'}, name='terms_of_use'),
    url(r'^privacy', direct_to_template, {'template':'privacy_policy.html'}, name='privacy_policy'),
    (r'^contact/', contact, {}, 'contact_us'),

)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^site-media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns('',
    url(r'(?P<username>[\w.-]+)/',view_port_for,name="portfolio_for_shortcut"),
    url(r'(?P<slug>[\w.-]+)/',list_detail.object_detail, company_detail,name="cportfolio_for_shortcut"),
)

adcake/portfolio/models.py
import random
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from countries.countries.models import Country
from helpers.utils import check_clean_cache
from multimedia.models import Playable, Video, Audio, Image,AdCategory
from directory.models import Company


class NotAuthoringException(Exception):
    """
    An user can only add to his portfolio media that he claimed
    author role for
    """
    pass

class PlayableElement(models.Model):
    portfolio = models.ForeignKey('Portfolio', related_name='playables')
    playable = models.ForeignKey(Playable, related_name='portfolios')
    position = models.IntegerField(max_length=4, editable=False, blank=True,
                                   null=True)

class CompanyPortfolio(models.Model):
    company = models.OneToOneField(Company, related_name='cportfolio')
    playable = models.ManyToManyField(Playable,null=True)
    video_position = models.PositiveIntegerField(max_length=1, default=1,
                                                 editable=False)
    audio_position = models.PositiveIntegerField(max_length=1, default=3,
                                                 editable=False)
    gallery_position = models.PositiveIntegerField(max_length=1, default=2,
                                                   editable=False)
    def contains(self,media):
     try:
        args = {'%s__pk' % media._meta.object_name.lower(): media.pk,}
        new_play = self.playable.get(**args)
     except Playable.DoesNotExist:
        return False
     return True
    
    def sorted_branches(self):
        """
        """
        from forms import GalleryForm, VideoAuthorForm, AudioForm
        from helpers.forms import add_helpful_classes
        branches = [
            { 'name': 'video',
              'plural_name': 'videos',
              'position': self.video_position,
              'featured_list':self._get_playable_type('video'),
              'form': VideoAuthorForm(user=self.company.owner)},
            { 'name': 'gallery',
              'plural_name': 'galleries',
              'position': self.gallery_position,
              'featured_list': self.galleries.all(),
              'form': GalleryForm(user=self.company.owner,cportfolio=self)},
            ]
        def branch_compare(b1, b2):
            if b1['position'] > b2['position']:
                return 1
            elif b1['position'] == b2['position']:
                return 0
            else:
                return -1
        branches.sort(cmp=branch_compare)
        return branches

    def _get_playable_type(self, pl_type):
        """
        Return a list of the videos or audios featured on the portfolio.
        It doesnt return a queryset because there's no way to filter
        through table inheritance
        """
        playables = []
        for pl in self.playable.all():
            try:
                pl = getattr(pl, pl_type)
                playables.append(pl)
            except:
                continue
        return playables
    def __unicode__(self):
        return '%s' % self.company
    
class Portfolio(models.Model):
    # TODO: tests...
    owner = models.OneToOneField(User, related_name='portfolio')
    playable_set = models.ManyToManyField(Playable, through=PlayableElement,
                                          blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    # For interface sortable branches
    video_position = models.PositiveIntegerField(max_length=1, default=1,
                                                 editable=False)
    audio_position = models.PositiveIntegerField(max_length=1, default=3,
                                                 editable=False)
    gallery_position = models.PositiveIntegerField(max_length=1, default=2,
                                                   editable=False)
    def _get_image_number(self):
        n = 0
        for gal in self.galleries.all():
            n = n + gal.image_count
        return n
    image_total = property(_get_image_number)
        
    def sorted_branches(self):
        """
        """
        from forms import GalleryForm, VideoAuthorForm, AudioForm, VideoAuthorFormWeb
        from helpers.forms import add_helpful_classes
        branches = [
            { 'name': 'video',
              'plural_name': 'videos',
              'all_link': reverse('videos_with', args=[self.owner.username, 1]),
              'position': self.video_position,
              'featured_list':self._get_playable_type('video'),
# Changed Temporally
#              'featured_list': self.videos,
              'unfeatured_list': self.unfeatured_videos, 
              'form': VideoAuthorFormWeb(user=self.owner)},

            { 'name': 'audio',
              'plural_name': 'audio tracks',
              'all_link': '',
              'position': self.audio_position,
              'featured_list': self.audios,
              'unfeatured_list': self.unfeatured_audios, 
              'form': AudioForm()},
            { 'name': 'gallery',
              'plural_name': 'galleries',
              'all_link': reverse('galleries_for', args=[self.owner.username]),
              'position': self.gallery_position,
              'featured_list': self.galleries.get_featured(),
              'unfeatured_list': self.galleries.get_unfeatured(), 
              'form': GalleryForm(user=self.owner) },
            ]
        def branch_compare(b1, b2):
            if b1['position'] > b2['position']:
                return 1
            elif b1['position'] == b2['position']:
                return 0
            else:
                return -1
        branches.sort(cmp=branch_compare)
        return branches

    def sorted_view_branches(self):
        """
        """
        from forms import GalleryForm, VideoAuthorForm, AudioForm, VideoAuthorFormWeb
        from helpers.forms import add_helpful_classes
        branches = [
            { 'name': 'video',
              'plural_name': 'videos',
              'all_link': reverse('videos_with', args=[self.owner.username, 1]),
              'position': self.video_position,
              #'featured_list':self._get_playable_type('video'),
              'featured_list':self.videos,
              'participation_list':self.participation_videos(),

            },
            { 'name': 'gallery',
              'plural_name': 'galleries',
              'all_link': reverse('galleries_for', args=[self.owner.username]),
              'position': self.gallery_position,
              #'featured_list': self.galleries.get_featured(),
              'featured_list': self.galleries.get_featured(),
             },
            ]
        def branch_compare(b1, b2):
            if b1['position'] > b2['position']:
                return 1
            elif b1['position'] == b2['position']:
                return 0
            else:
                return -1
        branches.sort(cmp=branch_compare)
        return branches

    def contains(self,media):
         try:
            args = {'playable__%s__pk' % media._meta.object_name.lower(): media.pk,}
            new_play = self.playables.get(**args)
         except PlayableElement.DoesNotExist:
            return False
         return True
    
    def set_featured_playable(self, media, position=None):
        """
        Sets the position in witch the playable has been added to the
        featured list.
        """
        if media._meta.module_name == 'gallery':
            media.set_as_featured(position=position)
            return media
        if position is None:
            try:
                last = self.playables.latest('position')
                position = last.position + 1
            except PlayableElement.DoesNotExist:
                position = 0
        try:
            args = {'playable__%s__pk' % media._meta.object_name.lower(): media.pk,}
            new_play = self.playables.get(**args)
            new_play.position = position
        except PlayableElement.DoesNotExist:
            new_play = PlayableElement(portfolio=self, playable=media,
                                       position=position)
        # Verify if the playable has an authorrole = portfolio.owner, if
        # it does then save the playable element, otherwise raise an exception
        if not new_play.playable.authors.filter(author=self.owner):
            raise NotAuthoringException()
        new_play.save()
        return new_play

    def unset_featured_playable(self, media):
        """
        Delete one playable from the featured list and restore the position
        in the rest of elements
        throws Playable.DoesNotExist
        """
        if media._meta.module_name == 'gallery':
            media.set_as_unfeatured()
            return media
        args = {'playable__%s__pk' % media._meta.object_name.lower(): media.pk,}
        playable = self.playables.get(**args)
        position = playable.position
        for pl in self.playables.order_by('-position'):
            if pl.position > position:
                pl.position = pl.position - 1
                pl.save()
            else:
                break
        playable.delete()
        return media
    def _get_playable_type(self, pl_type):
        """
        Return a list of the videos or audios featured on the portfolio.
        It doesnt return a queryset because there's no way to filter
        through table inheritance
        """
        playables = []
        for pl in self.playables.all():
            try:
                pl = getattr(pl.playable, pl_type)
                playables.append(pl)
            except:
                continue
        return playables
    def participation_videos(self):
        return Video.objects.filter(authors__author=self.owner).distinct().exclude(owner=self.owner)
    @property

adcake/templates/portfolio/base_gallery.html
{% extends "base.html" %}

      {% block menu %}
      <ul id="site-menu">
      {% load site_menu %}
      {% ifequal user owner %}
      {% main_menu "portfolio" %}
      {% else %}
      {% ifequal user image.owner %}
      {% main_menu "portfolio" %}
      {% else %}
      {% main_menu "" %}
      {% endifequal %}
      {% endifequal %}
      </ul>
      {% endblock %}

{% block extra-style %}<link href="{{ MEDIA_URL }}css/galleries.css" type="text/css" rel="stylesheet" rev="stylesheet" />{% endblock %}

{% block jslib %}{{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/galleries.js"></script>
    {# form.media #}
{% endblock %}

adcake/templates/portfolio/base_portfolio.html
{% extends "base.html" %}
      {% block menu %}
      <ul id="site-menu">
      {% load site_menu %}{% main_menu "portfolio" %}
      </ul>
      {% endblock %}
{% block jslib %}{{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/portfolio.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/portfolio2.js"></script>
{% endblock %}

adcake/templates/portfolio/creation.html
{% if form.errors %}
{% load uni_form thumbnail %}
	<form method="post" class="adcake-uni-form{% if not form.errors %} hide{% endif%}" id="add-{{ branch }}" action="{% url portfolio_xhr_create branch %}" enctype="multipart/form-data" target="frame-{{ branch }}">{% csrf_token %}
	  <fieldset class="inlineLabels">
            <legend>Add a new {{ branch }}</legend>
            {{ form|as_uni_form }}
        {% ifequal branch 'video' %}
        <input type="hidden" name="type" value="O"/>
        {% endifequal %}
	    <input type="hidden" name="branch" value="{{ branch }}" />
            <div class="buttonHolder">
              <input name="submit" type="submit" value="Add">
            </div>
            <span id="errors"></span>
	  </fieldset>
	  <iframe id="frame-{{ branch }}" name="frame-{{ branch }}" class="hidden-frame"></iframe>
	</form>
{% else %}
{% ifequal branch 'gallery' %}
<li id="gallery-id-{{ obj.pk }}">
      <div class="media-thumb-gallery">
	{% if obj.first_image %}
	<a href="{{ obj.get_absolute_url }}" title="View '{{ obj }}'">{{ obj.first_image.image.extra_thumbnails_tag.wide }}</a>
	{% else %}
	<a href="{{ obj.get_absolute_url }}" title="View '{{ obj }}'"><img src="{{ MEDIA_URL }}images/no-image-full.png" /></a>
	{% endif %}
      </div>
      <div class="media-info">
	<a href="{{ obj.get_absolute_url }}" title="View '{{ obj }}'" class="media-title">{{ obj }}</a>
	<div class="media-meta">
	      <span class="media-views">{{ obj.view_count }} view{{ obj.view_count|pluralize }}</span>
	</div>
      </div>
      {% ifequal obj.portfolio.owner user %}<a class="delete-gallery" href="#{{ obj.pk }}" title="Delete this gallery"></a>{% endifequal %}
      <span class="image-cont"></span>

</li>
{% endifequal %}
{% ifequal branch 'audio' %}
<li id="audio-id-{{ obj.pk }}">

  <span class="media-name"><a href="{{ obj.get_absolute_url }}" title="Hear '{{ obj }}'">{{ obj }} {{ obj.length }}</a></span>

</li>
{% endifequal %}
{% ifequal branch 'video' %}
<li id="video-id-{{ obj.pk }}">
	  <div class="media-thumb">
	    {% if obj.image %}
	    <a href="{{ obj.image.get_absolute_url }}" title="{{ obj }}">{{ obj.image.extra_thumbnails_tag.wide }}</a>
	    {% else %}
	    <a href="{% url video_detail obj.playable.video.pk obj.playable.video.slug %}" title="{{ obj }}">{% if obj.playable.video.get_thumbnails.0 %}<img src="{% thumbnail obj.playable.video.get_thumbnails.0 172x96 crop %}" />{% endif %}</a>
	    {% endif %}
	  </div>
	  <div class="media-info">
	    {% if obj.image %}
	    <a href="{{ obj.image.get_absolute_url }}" title="{{ obj }}" class="media-title">{{ obj }}</a>
	    {% else %}
	    <a href="{% url video_detail obj.playable.video.pk obj.playable.video.slug %}" title="{{ obj }}" class="media-title">{{ obj }}</a>
	    {% endif %}
	    <div class="media-meta">
	      <span class="media-owner">By: <a href="{{ obj.owner.get_profile.get_absolute_url }}" title="{{ obj.owner.get_profile.get_name }}'s profile">{{ obj.owner.get_profile.get_name }}</a></span> <br />
	      <span class="media-views">{{ obj.view_count }} view{{ obj.view_count|pluralize }}</span>
	    </div>
	  </div>
</li>
{% endifequal %}
{% endif %}
<script type="text/javascript">
    function send() {
	window.parent.Portfolio.recieveFromForm(document.body, "{{ branch }}-branch");
    }
window.onload=send;
</script>

adcake/templates/portfolio/edit.html
{% extends "portfolio/base_portfolio.html" %}

{% block title %}Edit your Portfolio{% endblock %}
{% load cake_buttons countries_tags %}
{% block content-header %}{% endblock %}
{% block content %}
<div id="owner-content">
   <div class="owner-image">
    {% if user.get_profile.image %}
    <img class="owner-image-avatar" src="{{ user.get_profile.image.extra_thumbnails.big }}" alt="{{ user }}" />
    {% else %}
    <img src="{{ MEDIA_URL }}images/no-avatar.png" alt="{{ user }}" width="64" height="64" />
    {% endif %}
  </div>
  <div class="owner-information large"{% ifequal user request.user %} style="padding-top: 0px"{% endifequal %}>
    <h1 class="owner-name">{{ user.get_profile.get_name }}'s Portfolio </h1>
    {% if user.get_profile.country %}
    <img class="flag" src="{{ user.get_profile.country.iso|iso_flag }}" alt="[{{ user.get_profile.country.iso }}]"/>
    <div class="clear"></div>
    {% endif %}
    <div class="profile-overview">
        <div class="profile-box"><div class="number">{{ user.get_profile.followers|length }}</div><div class="name">Followers</div></div>
        <div class="profile-box"><div class="number">{{ user.get_profile.following_count}}</div><div class="name">Following</div></div>
        <div class="profile-box"><div class="number">{{ user.get_profile.videos_count }}</div><div class="name">Videos</div></div>
        <div class="profile-box"><div class="number">{{ user.get_profile.galleries_count }}</div><div class="name">Galleries</div></div>
    </div>
    <div class="profile-overview-options">
        <div class="profile-overview-c1">
            {% ifnotequal request.user user %}
                {% add_to_contact_list user %}
                <a href="{% url messages_compose_to user.username %}" title="View {{ user.get_profile.get_name }}'s profile" class="send-message">Send a message</a>
            {% else %}
                <a href="{% url portfolio_for_shortcut user.username %}" title="Preview my portfolio" class="edit-portfolio">Preview Portfolio</a>
            {% endifnotequal %}
        </div>
        <div class="profile-overview-c2">
            <a href="{% url my_profile %}" title="View {{ user.get_profile.get_name }}'s profile" class="profile">Edit Profile</a>
        </div>
    </div>
  </div>
    <div class="clear"></div>
    <div class="share-portfolio">
        <span>Share your portfolio: <a href={% url portfolio_for_shortcut user.username  %}>http://www.adcake.com{% url portfolio_for_shortcut user.username  %}</a></span>
    </div>
    <div id="portfolio-information" class="edit">
        <span>About this portfolio:</span>
        <textarea id="portfolio-information"{% if not portfolio.description %} class="empty"{% endif %}>{% if portfolio.description %}{{ portfolio.description }}{% else %}Add a short description of your portfolio here...{% endif %}</textarea>
        <div class="clear"></div>
    </div>
</div>
<div id="portfolio" class="edit">
  <h2>Set your Current Work</h2>
  <ul id="media-branches">
    {% for branch in portfolio.sorted_branches %}
    <li id="{{ branch.name }}-branch">

      <div class="media-header">
	<h3 class="media-title">{{ branch.name|capfirst }} List</h3>
                <span class="sortable-handler"></span>
	<br class="clear" />
      </div>
      <div class="media-content">
      {% load thumbnail %}
    {% ifequal branch.name 'gallery' %}
	{% ifnotequal branch.name 'audio' %}<div class="add-media"><span class="collapsable-trigger{% if formg.errors %} open{% endif %}" rel="add-{{ branch.name }}" id="{{ branch.name }}-collapse">Add a new {{ branch.name|capfirst }}</span></div>{% endifnotequal %}
	{% load uni_form %}
	<form  method="post" class="adcake-uni-form{% if not formg.errors %} hide{% endif%}" id="add-{{ branch.name}}" style="display:none" enctype="multipart/form-data">{% csrf_token %}
	  <fieldset class="inlineLabels">
            <legend>Add a new {{ branch.name }}</legend>
            {{ formg|as_uni_form }}
	    <input type="hidden" name="branch" value="{{ branch.name }}" />
            <div class="buttonHolder">
              <input name="submit" type="submit" value="Add">
            </div>
            <span id="errors"></span>
	  </fieldset>
	</form>
    {% else %}
    {% ifnotequal branch.name 'audio' %}<div class="add-media"><span class="collapsable-trigger{% if formw.errors %} open{% endif %}" rel="add-video" id="{{ branch.name }}-collapse">Add a new {{ branch.name|capfirst }} from web</span></div>
	{% load uni_form %}
    <form method="post" class="adcake-uni-form" id="add-video" enctype="multipart/form-data" style="display:none">{% csrf_token %}
	  <fieldset class="inlineLabels">
            <legend>Add a new video from web</legend>
            {{ formw|as_uni_form }}
	    <input type="hidden" name="branch" value="{{ branch.name }}" />
        <input type="hidden" name="type" value="O"/>
            <div class="buttonHolder">
              <input name="submit" type="submit" value="Add">
            </div>
            <span id="errors"></span>
	  </fieldset>
	</form>
    {% endifnotequal %}
    {%  endifequal %}
	<ul id="{{ branch.name }}-list" class="edit-media-branches">
	  {% if branch.featured_list %}
	  {% ifequal branch.name 'video' %}{% include 'portfolio/lists/video_list.html' %}{% endifequal %}
	  {% ifequal branch.name 'audio' %}{% include 'portfolio/lists/audio_list.html' %}{% endifequal %}
	  {% ifequal branch.name 'gallery' %}{% include 'portfolio/lists/gallery_list.html' %}{% endifequal %}
	  {% else %}
	  <li class="empty-branch" style="width:100%">
	    The {{ branch.name|capfirst }} List is <strong>empty</strong>, this branch <strong>will not be shown</strong> in your
	    Portfolio View.
	  </li>
	  {% ifequal branch.name 'audio' %}<li class="comming-soon">This feature is comming soon.</li>{% endifequal %}
	  {% endif %}
	</ul>
    <div class="clean"></div>
      </div>
    </li>
    {% endfor %}
    {% block extra_js %}
        {% if not formg.errors %}
            <script type="text/javascript">
                new Fx.Slide('add-gallery').hide();
                $('add-gallery').set({styles: {display:'block'}})
            </script>
        {% else %}
            <script type="text/javascript">
                $('add-gallery').set({styles: {display:'block'}})
            </script>
        {% endif%}
        {% if not formw.errors %}
            <script type="text/javascript">
                new Fx.Slide('add-video').hide();
                $('add-video').set({styles: {display:'block'}})
            </script>
        {% else %}
            <script type="text/javascript">
                $('add-video').set({styles: {display:'block'}})
            </script>
        {% endif%}
    {% endblock %}
  </ul>
</div>
{% endblock %}

adcake/templates/portfolio/gallery_form.html
{% extends "portfolio/base_gallery.html" %}

{% block content-menu %}
<ul id="content-menu">
  <li><a href="{% url gallery_index 1 %}">All Galleries</a></li>
  <li><a href="{% url galleries_for user.username %}">View your galleries</a></li>
  {% if has_next %}
  <li><a href="{% url gallery_index next %}">Next Page</a></li>
  {% endif %}
  {% if has_previous %}
  <li><a href="{% url gallery_index previous %}">Previous Page</a></li>
  {% endif %}
</ul>
{% endblock %}

{% block content %}
{% load uni_form %}
<form method="post" class="adcake-uni-form" id="add-gallery">{% csrf_token %}
  <fieldset class="inlineLabels">
    <legend>Add a new gallery</legend>
    {{ form|as_uni_form }}
    <input type="hidden" name="portfolio" value="{{ user.portfolio.pk }}" id="id_portfolio" />
    <div class="buttonHolder">
      <input name="submit" type="submit" value="Add it">
    </div>
    <span id="errors"> </span>
  </fieldset>
</form>
{% endblock %}